services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: remax
      MYSQL_DATABASE: gestao_ferias_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
